cat Lab\ 1\ Workbook.ipynb |  jq '{cells:[  .cells[] | select(.cell_type=="raw" // .cell_type=="code" | not) ]} + del (.cells)' > Lab\ 1\ Workbook\ Student.ipynb
cat Lab\ 2\ Workbook.ipynb |  jq '{cells:[  .cells[] | select(.cell_type=="raw" // .cell_type=="code" | not) ]} + del (.cells)' > Lab\ 2\ Workbook\ Student.ipynb
cat Lab\ 3\ Workbook.ipynb |  jq '{cells:[  .cells[] | select(.cell_type=="raw" // .cell_type=="code" | not) ]} + del (.cells)' > Lab\ 3\ Workbook\ Student.ipynb
cat Lab\ 4\ Workbook.ipynb |  jq '{cells:[  .cells[] | select(.cell_type=="raw" // .cell_type=="code" | not) ]} + del (.cells)' > Lab\ 4\ Workbook\ Student.ipynb
cat Lab\ 5\ Workbook.ipynb |  jq '{cells:[  .cells[] | select(.cell_type=="raw" // .cell_type=="code" | not) ]} + del (.cells)' > Lab\ 5\ Workbook\ Student.ipynb
cat Lab\ 6\ Workbook.ipynb |  jq '{cells:[  .cells[] | select(.cell_type=="raw" // .cell_type=="code" | not) ]} + del (.cells)' > Lab\ 6\ Workbook\ Student.ipynb
cat Lab\ 7\ Workbook.ipynb |  jq '{cells:[  .cells[] | select(.cell_type=="raw" // .cell_type=="code" | not) ]} + del (.cells)' > Lab\ 7\ Workbook\ Student.ipynb
cat Lab\ 8\ Workbook.ipynb |  jq '{cells:[  .cells[] | select(.cell_type=="raw" // .cell_type=="code" | not) ]} + del (.cells)' > Lab\ 8\ Workbook\ Student.ipynb
cat Lab\ 9\ Workbook.ipynb |  jq '{cells:[  .cells[] | select(.cell_type=="raw" // .cell_type=="code" | not) ]} + del (.cells)' > Lab\ 9\ Workbook\ Student.ipynb
cat Lab\ 10\ Workbook.ipynb |  jq '{cells:[  .cells[] | select(.cell_type=="raw" // .cell_type=="code" | not) ]} + del (.cells)' > Lab\ 10\ Workbook\ Student.ipynb
cat Lab\ 11\ Workbook.ipynb |  jq '{cells:[  .cells[] | select(.cell_type=="raw" // .cell_type=="code" | not) ]} + del (.cells)' > Lab\ 11\ Workbook\ Student.ipynb
cat Lab\ 12\ Workbook.ipynb |  jq '{cells:[  .cells[] | select(.cell_type=="raw" // .cell_type=="code" | not) ]} + del (.cells)' > Lab\ 12\ Workbook\ Student.ipynb
cat Lab\ 13\ Workbook.ipynb |  jq '{cells:[  .cells[] | select(.cell_type=="raw" // .cell_type=="code" | not) ]} + del (.cells)' > Lab\ 13\ Workbook\ Student.ipynb
cat Lab\ 14\ Workbook.ipynb |  jq '{cells:[  .cells[] | select(.cell_type=="raw" // .cell_type=="code" | not) ]} + del (.cells)' > Lab\ 14\ Workbook\ Student.ipynb
cat Lab\ 15\ Workbook.ipynb |  jq '{cells:[  .cells[] | select(.cell_type=="raw" // .cell_type=="code" | not) ]} + del (.cells)' > Lab\ 15\ Workbook\ Student.ipynb
cat Lab\ 16\ Workbook.ipynb |  jq '{cells:[  .cells[] | select(.cell_type=="raw" // .cell_type=="code" | not) ]} + del (.cells)' > Lab\ 16\ Workbook\ Student.ipynb
cat Lab\ 17\ Workbook.ipynb |  jq '{cells:[  .cells[] | select(.cell_type=="raw" // .cell_type=="code" | not) ]} + del (.cells)' > Lab\ 17\ Workbook\ Student.ipynb
cat Lab\ 18\ Workbook.ipynb |  jq '{cells:[  .cells[] | select(.cell_type=="raw" // .cell_type=="code" | not) ]} + del (.cells)' > Lab\ 18\ Workbook\ Student.ipynb
